spring.application.name=lawconnect
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lawconnect_db
spring.datasource.username=lawconnect_user
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000

eureka.client.enabled=false
spring.devtools.restart.enabled=false

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=24h

# Actuator
management.endpoints.web.exposure.include=*

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.enabled=false

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ===== OAuth2 Google =====
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:your-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:your-secret}
spring.security.oauth2.client.registration.google.redirect-uri=https://lawconnect.duckdns.org/oauth2/callback/google
spring.security.oauth2.client.registration.google.scope=email,profile

# ===== Redirections post-login =====
app.oauth2.user-redirect-uri=https://lawconnect-frontend-z2jq.vercel.app/dashboard
app.oauth2.admin-redirect-uri=https://lawconnect-frontend-z2jq.vercel.app/admin/dashboard


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

lawconnect.mail.from-name=LawConnect

# ===== Resend (envoi email via API HTTP) =====
# resend.api.key=${RESEND_API_KEY}
# resend.from.email=onboarding@resend.dev

google.client.id=${GOOGLE_CLIENT_ID}

app.upload.dir=uploads/photos
app.upload.documents.dir=uploads/documents
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# ===== NotchPay =====
notchpay.base-url=https://api.notchpay.co
notchpay.public-key=${NOTCHPAY_PUBLIC_KEY:sb.pk_test_sample_key_12345}
notchpay.secret-key=${NOTCHPAY_SECRET_KEY:sb.sk_test_sample_key_67890}
notchpay.hash-key=${NOTCHPAY_HASH_KEY:sample_webhook_secret_key}
notchpay.currency=XAF
notchpay.callback-url=https://lawconnect.duckdns.org/api/v1/webhooks/notchpay
